steps:
  - template: tools.yml

  - task: Bash@3
    inputs:
      filePath: yarn-ci.sh
    displayName: yarn (install packages)

  - script: |
      yarn playwright install --with-deps
    displayName: Install Playwright dependencies

  - script: |
      yarn cypress verify
    displayName: verify cypress install

  - script: |
      yarn lage build --verbose
    displayName: build

  - script: |
      yarn lage bundle-size --verbose
    displayName: bundle-size

  - script: |
      yarn lage build-storybook --verbose
    displayName: build-storybook

  - script: |
      yarn lage bundle --verbose
    displayName: bundle

  - script: |
      yarn lage verify-packaging --verbose
    displayName: verify-packaging

  - script: |
      yarn lage lint --verbose
    displayName: lint

  - script: |
      yarn lage type-check --verbose
    displayName: type-check

  - script: |
      yarn lage test --verbose
    displayName: test

  - script: |
      yarn lage e2e --verbose
    displayName: e2e

  - script: |
      yarn lage test-ssr --verbose
    displayName: test-ssr

  - script: |
      yarn lage test-perf --verbose
    displayName: test-perf

  - script: |
      yarn lage vr:test --verbose
    displayName: test-vr

  - template: cleanup.yml
