defaultSemverRangePrefix: ''

enableTelemetry: false

nodeLinker: node-modules

npmRegistryServer: 'https://registry.npmjs.org/'

yarnPath: /Users/martinhochel/Projects/msft/fluentui/.yarn/releases/yarn-berry.js
