pr:
  - master

# There's a separate pipeline for CI which also uses this file, but with a trigger override in the UI
# https://dev.azure.com/uifabric/fabricpublic/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=164&view=Tab_Triggers
trigger: none

variables:
  - ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/heads/')) }}:
      - name: sinceArg
        value: --since $(targetBranch)

  - group: fabric-variables

  - template: .devops/templates/variables.yml

pool: '1ES-Host-Ubuntu'

jobs:
  - job: Lage_Tests
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - script: |
          yarn install
        displayName: yarn

      - script: |
          yarn lage test
        displayName: test

      - template: .devops/templates/cleanup.yml

  - job: Lage
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - script: |
          yarn install
        displayName: yarn

      - script: |
          yarn lage build test lint type-check
        displayName: build, test, lint, type-check

      - template: .devops/templates/cleanup.yml

  - job: Lage_Lint
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - script: |
          yarn install
        displayName: yarn

      - script: |
          yarn lage lint
        displayName: lint

      - template: .devops/templates/cleanup.yml

  - job: NX
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - script: |
          yarn install
        displayName: yarn

      - script: |
          yarn nx run-many --targets=build,test,lint,type-check --parallel=8
          # yarn affected:run --base=$(targetBranch) --target=build --target=test --target=lint --target=type-check
        displayName: build, test, lint, type-check

      - template: .devops/templates/cleanup.yml

  - job: Nx_Tests
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - script: |
          yarn install
        displayName: yarn

      - script: |
          yarn nx run-many --target=test --parallel=8 --maxWorkers=4
        displayName: test

      - template: .devops/templates/cleanup.yml

  - job: Nx_Lint
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - script: |
          yarn install
          git diff yarn.lock
          git diff package.json
        displayName: yarn

      - script: |
          yarn nx run-many --target=lint --parallel=8
        displayName: lint

      - template: .devops/templates/cleanup.yml

  - job: E2E_new
    displayName: E2E new
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - task: Bash@3
        inputs:
          filePath: yarn-ci.sh
        displayName: yarn

      - script: |
          yarn e2e $(sinceArg)
        displayName: Cypress E2E tests

      - template: .devops/templates/cleanup.yml

  - job: DeployE2E
    displayName: Deploy and E2E
    workspace:
      clean: all
    steps:
      - template: .devops/templates/tools.yml

      - task: Bash@3
        inputs:
          filePath: yarn-ci.sh
        displayName: yarn

      # this also builds FUI N* docs if appropriate
      - script: |
          yarn bundle  $(sinceArg)
        displayName: bundle

      - script: |
          yarn lage build-storybook  --verbose $(sinceArg)
        displayName: build Storybooks

      ## This runs regardless of scope, the app will adapt to the scope as well
      - script: |
          yarn workspace @fluentui/pr-deploy-site generate:site
        displayName: generate PR Deploy Site

      - task: AzureUpload@2
        displayName: Upload PR deploy site
        inputs:
          azureSubscription: $(azureSubscription)
          BlobPrefix: $(deployBasePath)
          ContainerName: '$web'
          SourcePath: 'apps/pr-deploy-site/dist'
          storage: $(azureStorage)

      - task: GithubPRStatus@0
        displayName: 'Update PR deploy site github status'
        inputs:
          githubOwner: microsoft
          githubRepo: fluentui
          githubContext: 'Pull request demo site'
          githubDescription: 'Click "Details" to go to the deployed demo site for this pull request'
          # This MUST have a trailing slash, or the links to PR deploy site assets won't work
          githubTargetLink: $(deployUrl)/

      - script: |
          yarn e2e $(sinceArg)
        displayName: Cypress E2E tests

      - template: .devops/templates/cleanup.yml
