[install]
# set default registry as a string
registry = "https://registry.npmjs.org"

[install.lockfile]
# whether to save a non-Bun lockfile alongside bun.lockb
# only "yarn" is supported
print = "yarn"
