name: VRT CI - Baseline

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  # see https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-only-cancel-in-progress-jobs-or-runs-for-the-current-workflow
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NX_PARALLEL: 6 # ubuntu-latest = 4-core CPU / 16 GB of RAM | macos-14-xlarge (arm) = 6-core CPU / 14 GB of RAM
  NX_PREFER_TS_NODE: true
  NX_VERBOSE_LOGGING: true

  # GitHub Secrets for Azure access
  # This service principal ("subscription" is a misleading name) only has access to the fluentuipr storage account
  AZURE_SUBSCRIPTION: Azure PR deploy - NEW
  AZURE_STORAGE: fluentuipr

permissions:
  contents: 'read'
  actions: 'read'

jobs:
  VisualRegressionTest_WebComponents:
    runs-on: ubuntu-latest
    env:
      pipelineId: '315'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run and publish VR screenshot
        uses: ./.github/actions/run-publish-vr-screenshot
        with:
          fluentVersion: webcomponents
          vrTestPackageName: 'vr-tests-web-components'
          vrTestPackagePath: 'apps/vr-tests-web-components'

      - name: Run Screenshotdiff update baseline
        uses: azure/cli@v2
        env:
          API_TOKEN: ${{ secrets.fabric-public-pipeline-access-PAT }}
          GITHUB_API_TOKEN: ${{ secrets.githubRepoStatusPAT }}
          VR_APP_API_URL: ${{ secrets.VR_APP_API_URL }}
          STORAGE_ACCOUNT_ID: ${{ secrets.StorageAccountId }}
          TENANT_ID: ${{ secrets.TenantId }}
          PRINCIPAL_CLIENT_ID: ${{ secrets.PrincipalClientId }}
          SERVICE_CONNECTION_ID: ${{ secrets.ServiceConnectionId }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          azcliversion: latest
          inlineScript: |
            npx vr-approval-cli@0.4.11 run-diff --buildType release --screenshotsDirectory ./screenshots --clientType "FLUENTUI" --locationPrefix 'FluentUI-web-components' --locationPostfix 'vrscreenshotwebcomponents' --pipelineId ${{ env.pipelineId }}

  VRToolUpdateBaseline_V9:
    runs-on: ubuntu-latest
    env:
      pipelineId: '311'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run and publish VR screenshot
        uses: ./.github/actions/run-publish-vr-screenshot
        with:
          fluentVersion: v9
          vrTestPackageName: 'vr-tests-react-components'
          vrTestPackagePath: 'apps/vr-tests-react-components'

      - name: Run Screenshotdiff update baseline
        uses: azure/cli@v2
        env:
          API_TOKEN: ${{ secrets.fabric-public-pipeline-access-PAT }}
          GITHUB_API_TOKEN: ${{ secrets.githubRepoStatusPAT }}
          VR_APP_API_URL: ${{ secrets.VR_APP_API_URL }}
          STORAGE_ACCOUNT_ID: ${{ secrets.StorageAccountId }}
          TENANT_ID: ${{ secrets.TenantId }}
          PRINCIPAL_CLIENT_ID: ${{ secrets.PrincipalClientId }}
          SERVICE_CONNECTION_ID: ${{ secrets.ServiceConnectionId }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          azcliversion: latest
          inlineScript: |
            npx vr-approval-cli@0.4.11 run-diff --buildType release --screenshotsDirectory ./screenshots --clientType "FLUENTUI" --locationPrefix 'fluentuiv9' --locationPostfix 'vrscreenshotv9' --pipelineId ${{ env.pipelineId }}

  VRToolUpdateBaseline_V8:
    runs-on: ubuntu-latest
    env:
      pipelineId: '312'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run and publish VR screenshot
        uses: ./.github/actions/run-publish-vr-screenshot
        with:
          fluentVersion: v8
          vrTestPackageName: 'vr-tests'
          vrTestPackagePath: 'apps/vr-tests'

      - name: Run Screenshotdiff update baseline
        uses: azure/cli@v2
        env:
          API_TOKEN: ${{ secrets.fabric-public-pipeline-access-PAT }}
          GITHUB_API_TOKEN: ${{ secrets.githubRepoStatusPAT }}
          VR_APP_API_URL: ${{ secrets.VR_APP_API_URL }}
          STORAGE_ACCOUNT_ID: ${{ secrets.StorageAccountId }}
          TENANT_ID: ${{ secrets.TenantId }}
          PRINCIPAL_CLIENT_ID: ${{ secrets.PrincipalClientId }}
          SERVICE_CONNECTION_ID: ${{ secrets.ServiceConnectionId }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          azcliversion: latest
          inlineScript: |
            npx vr-approval-cli@0.4.11 run-diff --buildType release --screenshotsDirectory ./screenshots --clientType "FLUENTUI" --locationPrefix 'fluentuiv8' --locationPostfix 'vrscreenshotv8' --pipelineId ${{ env.pipelineId }}

  VRToolUpdateBaseline_V0:
    runs-on: ubuntu-latest
    env:
      pipelineId: '313'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run and publish VR screenshot
        uses: ./.github/actions/run-publish-vr-screenshot
        with:
          fluentVersion: v0
          vrTestPackageName: 'docs'
          vrTestPackagePath: 'packages/fluentui/docs'

      - name: Run Screenshotdiff update baseline
        uses: azure/cli@v2
        env:
          API_TOKEN: ${{ secrets.fabric-public-pipeline-access-PAT }}
          GITHUB_API_TOKEN: ${{ secrets.githubRepoStatusPAT }}
          VR_APP_API_URL: ${{ secrets.VR_APP_API_URL }}
          STORAGE_ACCOUNT_ID: ${{ secrets.StorageAccountId }}
          TENANT_ID: ${{ secrets.TenantId }}
          PRINCIPAL_CLIENT_ID: ${{ secrets.PrincipalClientId }}
          SERVICE_CONNECTION_ID: ${{ secrets.ServiceConnectionId }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          azcliversion: latest
          inlineScript: |
            npx vr-approval-cli@0.4.11 run-diff --buildType release --screenshotsDirectory ./screenshots --clientType "FLUENTUI" --locationPrefix 'FluentUI-v0' --locationPostfix 'vrscreenshotv0' --pipelineId ${{ env.pipelineId }}
